version: '3.7'

# Define services
services:
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    build:
      context: ../backend # Use an image built from the specified dockerfile in the `backend` directory.
      dockerfile: Dockerfile
    ports:
      - "${SERVER_APP_PORT}:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    depends_on: 
      - database # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://database:${DB_PORT}/mysqldb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root    
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  # Frontend Service 
  app-client:
    build:
      context: ../frontend # Use an image built from the specified dockerfile in the `frontend` directory.
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: https://api.eventus.space
    ports:
      - "${CLIENT_APP_PORT}:80" # Map the exposed port 8000 on the container to port 9090 on the host machine
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend  

  # Database Service (Mysql)
  database:
    image: mariadb:latest
    ports:
        - "${DB_PORT}:3306"
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mysqldb
        MYSQL_USER: user
        MYSQL_PASSWORD: user
    networks:
      - backend

  
# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:    
    
