# This workflow will launch the frontend and backend tests when changes are detected in the develop or main branches.
# It also start a static analysis and coverage analysis from Codacy

name: EventUS CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build_backend:
    name: Build Backend
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mysqldb
          MYSQL_USER: user
          MYSQL_PASSWORD: user
        ports:
        - '3306:3306'
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
    
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Maven
      run: |
        mvn --batch-mode --update-snapshots verify
    #This step will share coverage data to codacy-coverage-reporter job
    - uses: actions/upload-artifact@v2
      with:
        name: backend-coverage
        path: backend/target/site/jacoco/jacoco.xml
  
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
    - uses: actions/checkout@v2
    - name: Setup node 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install frontend dependencies
      run: 
        npm install
    - name: Run frontend tests with coverage
      run:
        npm run coverage
  
  codacy-coverage-reporter:
    #This jobs sends frontend and backend coverage data to Codacy servers, so it must be execute after both builds
    needs: [ build_backend, build-frontend ]
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: backend-coverage
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: 'jacoco.xml'
